attacker_cls: "GCGAttacker"
attacker_name: "GCG"
llm_config:
  llm_type: "HuggingFaceLLM"
  model_name: "meta-llama/Llama-3.2-1B-Instruct"
  device_map: "cuda:6"
llm_gen_config:
  max_n_tokens: 150
  temperature: 1.0
  logprobs: False
  seed: null
search_width: 512
batch_size: null
topk: 256
adv_string_init: "x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x"
num_steps: 250
n_replace: 1
buffer_size: 0
use_mellowmax: False
mellowmax_alpha: 1.0
early_stop: False
use_prefix_cache: True
allow_non_ascii: False
filter_ids: True
add_space_before_target: False
seed: null