attacker_cls: "GPTFuzzAttacker"
attacker_name: "GPTFuzz"

# attacker llm configs
attacker_llm_config:
  llm_type: "HuggingFaceLLM"
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  device_map: cuda:0

# The original paper's configuration:
# llm_type: "OpenAiChatLLM"
# model_name: "gpt-3.5-turbo"

attacker_llm_gen_config:
  max_n_tokens: 1000
  temperature: 1.0
  logprobs: False
  seed: null

# target llm configs
target_llm_config:
  llm_type: "HuggingFaceLLM"
  model_name: "meta-llama/Llama-3.2-8B-Instruct"
target_llm_gen_config:
  max_n_tokens: 1000
  temperature: 1.0
  logprobs: False
  seed: null

# 77 jailbreak templates as initial seed
initial_seed: "../../data/GPTFuzz/GPTFuzzer.csv"

# Pre-trained model for determining whether a jailbreak was successful or not
predict_model: 'hubert233/GPTFuzz'