defender_cls: "PerplexityFilterDefender"
target_llm_config:
  llm_type: "OpenAiLLM"
  model_name: "meta-llama/Meta-Llama-3.1-70B-Instruct"
  base_url: "http://172.18.129.80:8000/v1"
target_llm_gen_config:
  max_n_tokens: 150
  temperature: 1.0
  logprobs: False
  seed: null
filter_llm_config:
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  llm_type: "OpenAiLLM"
  base_url: "http://172.18.131.18:8000/v1"
#  api_key: "token-casia-braincog-233"
filter_llm_gen_config:
  max_n_tokens: 0
  temperature: 1.0
  logprobs: True
  seed: null
threshold: 500