defender_cls: RPODefender
defender_name: RPO

# target LLM
target_llm_config:
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.2-1B-Instruct
  device_map: cuda:0
target_llm_gen_config:
  max_n_tokens: 128
  temperature: 1.0
  logprobs: false
  seed: 42